# SPDX-FileCopyrightText: 2024 Mass Labs
#
# SPDX-License-Identifier: GPL-3.0-or-later

[profile.default]
src = 'src'
out = 'out'
script = 'script'
libs = ['lib']

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
