# SPDX-FileCopyrightText: 2024 Mass Labs
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: test
on: [push]
jobs:
  solidity-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      anvil:
        image: ghcr.io/foundry-rs/foundry:latest
        ports:
          - 8545:8545
        options: --entrypoint anvil
        env:
          ANVIL_IP_ADDR: 0.0.0.0
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run Checks
        run: nix flake check .
      - name: Run Tests
        run: nix build .#mass-contracts  --log-lines 0 --print-build-logs
