name: test
run-name: ${{ github.actor }} is running Foundry tests
on: [push]
jobs:
  solidity-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run Tests
        run: nix develop -c forge test --no-auto-detect
